In [1]:
#5 marks
import numpy as np
x1 = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
x2 = np.array([ [10,20,30],[40,50,60],[70,80,90] ])

result = []
for i in range(len(x1)):
    row = []
    for j in range(len(x1[0])):
        row.append(x1[i][j] + x2[i][j])
    result.append(row)

#print the result
for i in result:
    for j in i:
        print(j, end = " ")
    print()

11 22 33 
44 55 66 
77 88 99 


In [4]:
#define a function for the above code
import numpy as np
x1 = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
x2 = np.array([ [10,20,30],[40,50,60],[70,80,90] ])

def addition_matrix(x1,x2):
    result = []
    for i in range(len(x1)):
        row = []
        for j in range(len(x1[0])):
            row.append(x1[i][j] + x2[i][j])
        result.append(row)

#print the result
for i in result:
    for j in i:
        print(j, end = " ")
    print()
addition_matrix(x1,x2)

11 22 33 
44 55 66 
77 88 99 


In [3]:
#2 Marks
import numpy as np
x1 = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
x2 = np.array([ [10,20,30],[40,50,60],[70,80,90] ])
print (x1+x2)

[[11 22 33]
 [44 55 66]
 [77 88 99]]
