In [1]:
#Matrix Multiplication using Dot Operator
import numpy as np
x1 = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
x2 = np.array([ [10,20,30],[40,50,60],[70,80,90] ])
result = np.dot(x1,x2)
print (result)

[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


In [3]:
#Matrix Multiplication using Nested Loops
import numpy as np
x1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

#Initialize an empty list for the result
result = []

#Perform matrix multiplication using nested loops
for i in range(len(x1)):  # Loop through rows of x1
    row = []
    for j in range(len(x2[0])):  # Loop through columns of x2
        sum_val = 0
        for k in range(len(x1[0])):  # Loop through elements for multiplication
            sum_val += x1[i][k] * x2[k][j]
        row.append(sum_val)
    result.append(row)

# Print the result in matrix format
for i in result:
    for j in i:
        print(j, end=" ")
    print()

300 360 420 
660 810 960 
1020 1260 1500 
