In [1]:
import numpy as np
x1 = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
x2 = np.array([ [10,20,30],[40,50,60],[70,80,90] ])
result = np.dot(x1,x2)
print (result)

[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


In [ ]:
#do the above code using nested loop just like the addition one

In [2]:
import numpy as np
x1 = np.array([ [1,2,3],[4,5,6] ])
result = np.transpose(x1)
result

array([[1, 4],
       [2, 5],
       [3, 6]])